export const IS_LOADING = "IS_LOADING";
export const IS_NOT_LOADING = "IS_NOT_LOADING";
export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_PHOTO_ALBUM = "FETCH_PHOTO_ALBUM";
export const FETCH_VIDEO_LIBRARY = "FETCH_VIDEO_LIBRARY";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_DOCUMENT_LIBRARY = "FETCH_DOCUMENT_LIBRARY";
